# Generated by Django 3.0.5 on 2020-11-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lotto',
            fields=[
                ('Draw', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Ball_1', models.FloatField()),
                ('Ball_2', models.FloatField()),
                ('Ball_3', models.FloatField()),
                ('Ball_4', models.FloatField()),
                ('Ball_5', models.FloatField()),
                ('Ball_6', models.FloatField()),
                ('Bonus', models.FloatField()),
                ('Powerball', models.FloatField()),
                ('Sorted', models.BinaryField()),
                ('Multivariable', models.BinaryField()),
                ('Version', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
